### ISSUE TITLE
problem.txt has no content except "undefined"

### ISSUE THREAD

**Issue by Mensu** [iebb/Maban#2]
It might simply be a minor mistake lying [here](https://github.com/iebb/Maban/blob/master/dl.js#L43) :) body.content -> body.data.content
And I really appreciate your idea of using json to simplify the process of fetching files! Reading your codes is such a pleasure and in the meanwhile I learn a lot from you 👍

**Comment by iebb** [comment]
a typo, fixed :+1: 
much thanks :100:
